### ISSUE TITLE
JSX and validateQuoteMarks issue

### ISSUE THREAD

**Issue by sebastienbarre** [jscs-dev/babel-jscs#12]
First, thanks for the great work. I just switched from using `esprima-fb` to `babel-jscs` (with `jscs-dev/node-jscs#master`). I'm experiencing some issues with React/JSX code:

```
class CardHeader extends PureRender {
  render() {
    return <div className="flex-card__header">{this.props.children}</div>;
  }
}
```

More specifically, `validateQuoteMarks` is being triggered (even if I set it to `true`):

```
validateQuoteMarks: Invalid quote mark found at src/js/components/CardHeader.react.js :
     6 |class CardHeader extends PureRender {
     7 |  render() {
     8 |    return <div className="flex-card__header">{this.props.children}</div>;
----------------------------------^
```

I'm using single quotes in my JavaScript, but quotes in JSX, per customary.
I've ESLint and babel-eslint at the same time, but not issue there.
Any hints?
Thanks

**Comment by hzoo** [comment]
The rule is checking for all quotes so currently it doesn't knowing if it's in JSX or not. So you didn't have this issue with `esprima-fb`? If you did then it's not really specific to `babel-jscs`.

It's a valid request but something will have to be changed to support it since we don't have any JSX specific rules so this wasn't an issue before.

There's actually an issue in eslint to enforce quotes for JSX https://github.com/eslint/eslint/issues/2011

Also `eslint-plugin-react` has a seperate rule for jsx-quotes: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-quotes.md

Maybe we should also do something like `eslint-plugin-react` - like a `jscs-plugin-react` with react specific rules.

**Comment by sebastienbarre** [comment]
Thanks for the quick reply. I didn't have this issue with `esprima-fb`, no, but this didn't surprise me, since it was responsible for parsing JSX, right? I assumed that by switching to `babel` to parse ES6/ES7 and JSX I was probably  going to experience a different behavior. 

Or could this be related to that recent commit that was also about `validateQuoteMarks`? (I reverted to 1.0.3 but same issue). 

Is there any way to disable `validateQuoteMarks` until this is eventually addressed? Setting it to `false` had no effect.

**Comment by hzoo** [comment]
The recent commit was actually to fix the rule because it wasn't erroring at all. You actually can disable any rules through putting `null` not false. Should be in the docs now http://jscs.info/overview.html#presets

So this would be fixed upstream in jscs - probably as an option to the rule to check jsx quotes separately or if not as a separate rule.

**Comment by sebastienbarre** [comment]
That did the trick, thank you.

**Comment by DanLipsitt** [comment]
I just cross-filed this as jscs-dev/node-jscs#1953.

**Comment by hzoo** [comment]
Ok closing in favor of ^ (a new rule option in jscs)

**Comment by DanLipsitt** [comment]
> Ok closing in favor of ^ (a new rule option in jscs)

I'm looking for that in the jscs project but it's a hard thing to search for. Can you point me in the right direction? 

Note that there is a patch in progress at jscs-dev/node-jscs#1953 that might also be relevant.

**Comment by hzoo** [comment]
Yeah that's what I mean - the issue you made and that PR

**Comment by DanLipsitt** [comment]
OK, gotcha. I thought you were talking about a rule option literally involving the caret symbol ('^'). :stuck_out_tongue_closed_eyes:

**Comment by hzoo** [comment]
Haha
