### ISSUE TITLE
disallowSpaceAfterObjectKeys rule is breaking babel stage 1 code  

### ISSUE THREAD

**Issue by okonet** [jscs-dev/babel-jscs#13]
After upgrade to 2.0 this code sample:

```
let newItem = {
    ...item,
    gridConfig: this.getGridConfigForWidget(item.id),
    appliedFiltersCount: this.getMultiFilters(item.id).length
}
```

is converted (invalid) to 

```
let newItem = {
    ...item,gridConfig: this.getGridConfigForWidget(item.id),
    appliedFiltersCount: this.getMultiFilters(item.id).length
}
```

when using `-x` option. It was working fine with 1.0.3.

Here is the sample output when running the check without `-x`

```
disallowSpaceAfterObjectKeys: Illegal space after key at ./js/modules/Dashboard/stores/DashboardStore.js :
   175 |            // This is needed for Angular view to funciton properly
   176 |            let newItem = {
   177 |                ...item,
--------------------------------^
   178 |                gridConfig: this.getGridConfigForWidget(item.id),
   179 |                appliedFiltersCount: this.getMultiFilters(item.id).length
```

**Comment by okonet** [comment]
Hmmm, I've downgraded to 1.0.3 but still have this issue. It seems the update of `node-jscs` to latest master broke it. Not sure yet.

**Comment by okonet** [comment]
Related issue: https://github.com/jscs-dev/node-jscs/pull/992

**Comment by okonet** [comment]
Looks like it's because of the spread operator.

**Comment by hzoo** [comment]
2.0.0 will be out today I think. Also I would recommend just using a specific commit instead of master (although I did put you can do that)

So like `"jscs": "jscs-dev/node-jscs#4d7043",`

Ok so your saying it's an autofix issue with that rule. Although that's not an es6 rule actually (https://github.com/sebmarkbage/ecmascript-rest-spread - es7). The only workaround would be to make a new rule/replacement rule for babel-jscs since I don't know if we are willing to update the rule itself (@markelog)

Thats what was done for eslint since they didn't want to modify the actual rules. https://github.com/babel/eslint-plugin-babel

**Comment by markelog** [comment]
> 2.0.0 will be out today I think. 

A lot to do today, only changelog would take some considerable time.

**Comment by markelog** [comment]
> The only workaround would be to make a new rule/replacement rule for babel-jscs since I don't know if we are willing to update the rule itself 

Would wait until it gets to second stage, @okonet you're welcome to make necessary changes now though

**Comment by hzoo** [comment]
Maybe we can do it collaboratively (changelog) since there seems to be a lot of changes and things to say (deprecated rules/etc), new docs/features.

The main question for us it if we want to support the newer stage 0 features in jscs itself or allow someone to separate rule that would account for it (so no maintenance burden) like I mentioned above.

**Comment by markelog** [comment]
> Maybe we can do it collaboratively (changelog) since there seems to be a lot of changes and things to say (deprecated rules/etc), new docs/features.

We usually do, will you add you to the list of reviewers.

> The main question for us it if we want to support the newer stage 0 features in jscs itself or allow someone to separate rule that would account for it (so no maintenance burden) like I mentioned above.

You mean do we want to add to the dist, or tell ppl to make it as a plugin? I'd say we could support it but not create it.

Although it is for all of us to discuss. @zxqfox, @mdevils @mikesherov @mrjoelkemp?

**Comment by hzoo** [comment]
Yeah I mean to make a plugin like https://github.com/babel/eslint-plugin-babel if we don't want to add it to the rule itself.

**Comment by mrjoelkemp** [comment]
> Although it is for all of us to discuss. @zxqfox, @mdevils @mikesherov @mrjoelkemp?

Can we create an issue on JSCS proper to discuss this?

**Comment by hzoo** [comment]
This is actually closed by https://github.com/jscs-dev/node-jscs/pull/1625 and should be in the next release (although I should check if that fix needs to be added to any more rules)
